### ISSUE TITLE
Add restart opt

### ISSUE THREAD

**Issue by Badgie** [cogitantium/chwifi#13]
Restarting connection is currently not supported and it is required to use `netctl`. Restart opts e.g. `chwifi -r home | work`, or simply `chwifi -r` with automatic detection of active profile could be a solution.

**Comment by falkecarlsen** [comment]
@Badgie, now fixed! You can say `chwifi -r $profile` or `chwifi restart $profile`.
Unfortunately it doesn't support automatic profile detection yet, as that would require iterating through all profiles with an `netctl is-active $profile` and checking whether only one is active. 

This is problematic, as `netctl-auto` can manage multiple profiles which can be bound to one or more interfaces and this may break some users more elaborate network setups.
